django_pagarme/urls.py
from django.urls import path

from django_pagarme import views

app_name = 'django_pagarme'
urlpatterns = [
    path('capture/<slug:slug>/<str:token>', views.capture, name='capture'),
    path('obrigado/<slug:slug>', views.thanks, name='thanks'),
    path('indisponivel/<slug:slug>', views.unavailable, name='unavailable'),
    path('one_click/<slug:slug>', views.one_click, name='one_click'),
    path('notification/<slug:slug>', views.notification, name='notification'),
    path('pagarme/<slug:slug>', views.pagarme, name='pagarme'),
    path('<slug:slug>', views.contact_info, name='contact_info'),
    path('subscription/<slug:slug>', views.subscription, name='subscription'),
    path('subscribe/<slug:slug>', views.subscribe, name='subscribe'),
    path(
        'subscription_payment_bank_slip/<int:transaction_id>',
        views.subscription_payment_bank_slip,
        name='subscription_payment_bank_slip'
    ),
]

django_pagarme/templates/django_pagarme/pagarme_js_form.html
{% load django_pagarme %}
{% csrf_token %}
<script type="application/javascript">
    var csfr_token = document.querySelector('[name=csrfmiddlewaretoken]').value
    var button = document.querySelector('.pay-button');

    function initiateCheckout() {
        {# inicia a instância do checkout #}
        var checkout = new PagarMeCheckout.Checkout({
            encryption_key: '{{CHAVE_PAGARME_CRIPTOGRAFIA_PUBLICA}}',
            success: function (data) {
                {# This is here because django will not allow creating url without slug #}
                {% if payment_item %}
                    let url = '{% url 'django_pagarme:capture' slug=payment_item.slug token='f' %}';
                    url = url.substring(0, url.length - 1);
                    window.location.href = url + data['token'];
                {% elif plan %}
                    let url = '{% url 'django_pagarme:subscribe' slug=plan.slug %}';
                    let ajax = new XMLHttpRequest();
                    ajax.open('POST', url, true);
                    ajax.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
                    ajax.send(JSON.stringify(data));
                    ajax.onreadystatechange = function() {
                        if (ajax.readyState == 4 && ajax.status == 200) {
                            console.log('Success');
                            window.location.href = ajax.response;
                        }
                    }
                {% endif %}
            },
            error: function (err) {
                console.log(err);
            },
            close: function () {
                console.log('The modal has been closed.');
            }
        });
        {#Obs.: é necessário passar os valores boolean como string#}
        checkout.open({
            buttonText: 'Pagar',
            buttonClass: 'botao-pagamento',
            customerData: {% if review_informations %}'true'{% else %}'false'{% endif %},
            reviewInformations: {% if review_informations %}'true'{% else %}'false'{% endif %},
            createToken: {% if plan %}'false'{% else %}'true'{% endif %},
            postback_url: '{{postback_url}}',
            {% if payment_item %}
                amount: {{payment_item.price}},
                paymentMethods: '{{payment_item.default_config.payments_methods}}',
                maxInstallments: {{payment_item.default_config.max_installments}},
                defaultInstallment: {{payment_item.default_config.default_installment}},
                freeInstallments: {{payment_item.default_config.free_installment}},
                interestRate: {{payment_item.default_config.interest_rate|interest_rate}},
                items: [
                    {
                        id: '{{payment_item.slug}}',
                        title: '{{payment_item.name}}',
                        unit_price: {{payment_item.price}},
                        quantity: 1,
                        tangible: '{{payment_item.tangible|lower}}'
                    }
                ]
            {% elif plan %}
                amount: {{plan.amount}},
                paymentMethods: '{{plan.payment_methods}}'
            {% endif %}
            {% if customer %}
                ,
                customer: {
                    external_id: '{{customer.external_id}}',
                    name: '{{customer.name}}',
                    email: '{{customer.email}}',
                    type: '{{ customer.type }}',
                    country: '{{customer.country}}',
                    documents: [{
                        type: '{{customer.document.type}}',
                        number: '{{customer.document.number}}'
                    }]{% if customer.phone %},
                        phone_numbers: ['{{customer.phone}}']
                    {% endif %}
                }
            {% endif %}
            {% if address %}
                ,
                billing: {
                    name: '{{customer.name}}',
                    address: {
                        country: '{{ address.country }}',
                        state: '{{ address.state }}',
                        city: '{{ address.city }}',
                        neighborhood: '{{ address.neighborhood }}',
                        street_number: '{{ address.street_number }}',
                        street: '{{ address.street }}',
                        zipcode: '{{ address.zipcode }}'
                        {% if complementary %},
                            complementary: '{{  complementary}}'
                        {% endif %}
                    }
                }
            {% endif %}
        });
    }

    {# Abrir o modal ao clicar no botão #}
    button.addEventListener('click', initiateCheckout);
    {% if open_modal %}
        window.addEventListener('load', function () {
            {# Workaroung because of TypeError: PagarMeCheckout.Checkout is not a constructor when proccenting right away #}
            setTimeout(initiateCheckout, 1000);
        });
    {% endif %}
</script>